[package]
name = "rendezvous"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.5.15", features = ["headers"] }
base64ct = { version = "1.5.2", features = ["std"] }
bytes = "1.2.1"
headers = "0.3.8"
mime = "0.3.14"
sha2 = "0.10.5"
time = "0.3.14"
tokio = { version = "1.21.0", features = ["sync"] }
tracing = "0.1.36"
uuid = { version = "1.1.2", features = ["v4", "fast-rng", "serde"] }

[workspace]
members = ["server", "synapse"]
