[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = { version = "0.14.20", features = ["server"] }
tokio = { version = "1.21.0", features = ["macros", "rt-multi-thread"] }
tracing-subscriber = "0.3.15"

rendezvous = { path = "../" }
