name: Python

on:
  push:
    branches: [ main ]
    tags: 
      - "*"
  pull_request:

jobs:
  build-wheels:
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: x86_64-macos-darwin
            compatibility: ignored

          - os: macos-latest
            target: aarch64-macos-darwin
            compatibility: ignored

          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            compatibility: manylinux2014

          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            compatibility: manylinux2014

          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
            compatibility: musllinux_1_2

          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            compatibility: musllinux_1_2

          - os: windows-latest
            target: x86_64-pc-windows-msvc
            compatibility: ignored

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Install Python 3.7
        uses: actions/setup-python@v4
        id: cpy37
        with:
          python-version: "3.7"
          architecture: x64
          update-environment: false

      - name: Install Python 3.8
        uses: actions/setup-python@v4
        id: cpy38
        with:
          python-version: "3.8"
          architecture: x64
          update-environment: false

      - name: Install Python 3.9
        uses: actions/setup-python@v4
        id: cpy39
        with:
          python-version: "3.9"
          architecture: x64
          update-environment: false

      - name: Install Python 3.10
        uses: actions/setup-python@v4
        id: cpy310
        with:
          python-version: "3.10"
          architecture: x64
          update-environment: false

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v1

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          default: true
          target: ${{ matrix.target }}

      - name: Install maturin
        run: pip install maturin[zig] --user

      - name: Build wheels
        run: |
          maturin build \
            --release \
            --out dist \
            --manifest-path synapse/Cargo.toml \
            -i ${{ steps.cpy37.outputs.python-path }} \
            -i ${{ steps.cpy38.outputs.python-path }} \
            -i ${{ steps.cpy39.outputs.python-path }} \
            -i ${{ steps.cpy310.outputs.python-path }} \
            --compatibility ${{ matrix.compatibility }} \
            --zig

      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: dist
